Repository OpenTekHub/blockchain, pull requests merged in 2024-09, with the labels that each got.

#11 Added LICENSE
  LICENSE
Labels: documentation, good first issue, wob24, level1

#14 Add Code of Conduct #1
  CODE_OF_CONDUCT.md
Labels: documentation, wob24, level1

#20 Crypto Symbol Accessibility[Issue #19]
  index.html
  script.js
Labels: enhancement, wob24, level2

#23 Template for Issues
  Issue_Template.md
Labels: good first issue, wob24, level1

#30 Added dropdown options for crypto currencies in the new UI
  index.html
  script.js
  styles.css
Labels: enhancement, wob24, level3
