Repository OpenTekHub/blockchain, pull requests merged in 2024-10, with the labels that each got.

#32 Add Github Greetings bot
  .github/workflows/greet-issues.yml
  .github/workflows/greet-pr.yml
Labels: wob24, level1

#33 Improved basic stylings and made it mobile responsive
  styles.css
Labels: bug, wob24, level3

#34 Improved contribution guidelines
  README.md
Labels: documentation, wob24, level1

#39 Add LEARN.md documentation for project setup and usage
  LEARN.md
Labels: documentation, wob24, level1

#38 added telegram bot link to website
  index.html
  script.js
  styles.css
Labels: enhancement, wob24, level3

#89 Create CONTRIBUTING.md issue no #62 Resolved
  CONTRIBUTING.md
Labels: level1, gssoc-ext

#121 ISSUE #48 Fixed the Footer UI
  index.html
  script.js
  styles.css
Labels: level2, hacktoberfest, gssoc-ext

#136 Updated FAQ enhancements
  index.html
  styles.css
Labels: help wanted, level2, hacktoberfest, gssoc-ext

#130 change the ui of the navbar
  index.html
  script.js
  styles.css
Labels: level2, hacktoberfest, gssoc-ext
